version: 2
jobs:
  build:
    working_directory: ~/austin-traffic-incidents
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies

      - run:
          name: Installing All Packages
          command: yarn

      - run:
          name: TypeScript Linter
          command: mkdir reports && yarn lint:ci

      - run:
          name: Running tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/test-results.xml"

      - run:
          name: Running test coverage
          command: yarn test:coverage:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/test-coverage.xml"

      - run:
          name: Set up AWS credentials and Amplify environment
          command: yarn aws:creds && yarn aws:init

      - run:
          name: Build Bundle for Distribution
          command: yarn build

      - run:
          name: Run Danger
          command: yarn danger:ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/

      - persist_to_workspace:
          root: ./
          paths:
            - ./

  deploy-fe-env:
    working_directory: ~/austin-traffic-incidents
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Deploy UI Bundle
          command: yarn aws:deploy:ui

  deploy-fe-prod:
    working_directory: ~/austin-traffic-incidents
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Deploy UI Bundle
          command: yarn aws:deploy:ui

workflows:
  version: 2
  austin-traffic-incident:
    jobs:
      - build:
          context: maingot
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - deploy-fe-env:
          context: maingot
          requires:
            - build
          filters:
            branches:
              only: /^(?!production).*$/
            tags:
              ignore: /.*/

      - deploy-fe-prod:
          context: maingot
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(v\d+)\.\d+.(\d+)$/
